# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet publish -c Release
        
      - name: Create bot directory
        run: mkdir /bot
          
      - name: Copy files to directory
        run: cp -rf NdvBot/bin/Release/net5.0/publish/* /bot/
     
      - name: Create service file
        run: printf "[Unit]\nDescription=\"Manages discord bot\"\n[Service]\nExecStart=/bot/NdvBot\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/discordbot.service
           
      - name: Reload daemon
        run: systemctl daemon-reload
        
      - name: Start bot
        run: systemctl restart discordbot
        
